name: 'Init build openwrt environment'
inputs:
  token:
    description: 'Telegram robot token.'
    required: true
  chatid:
    description: 'Notify chat.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'

    - name: Initialization Environment
      shell: bash
      run: |
        sudo apt -y update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3 python3-distutils rsync unzip zlib1g-dev file wget netcat tree libpcre3 libpcre3-dev swig xsltproc

    - name: Check Space
      shell: bash
      run: |
        echo "INIT_BUILD_SPACE=$(df -h | tail -1 | awk '{print $4}')" >> $GITHUB_ENV
        echo "MOUNT_DIR=$(df -h | tail -1 | awk '{print $6}')" >> $GITHUB_ENV
  
    - name: Notify init result
      uses: appleboy/telegram-action@master
      with:
        token: ${{ inputs.token }}
        to: ${{ inputs.chatid }}
        message: Clear ${{ env.INIT_BUILD_SPACE }} at ${{ env.MOUNT_DIR }}.
