name: 'Set build openwrt online log'
inputs:
  token:
    description: 'Telegram robot token.'
    required: true
  chatid:
    description: 'Notify chat.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Start stream build log
      shell: bash
      run: |
        touch build.log
        nohup tail -f build.log | nc seashells.io 1337 > server.log 2>&1 &
        sleep 3s
        echo "SEASHELLS_URL=$(head -1 server.log | awk '{print $NF}')" >> $GITHUB_ENV

    - name: Notify stream url
      uses: appleboy/telegram-action@master
      with:
        token: ${{ inputs.token }}
        to: ${{ inputs.chatid }}
        message:  |
          The online log link : 
          ${{ env.SEASHELLS_URL }}.
          And monitor set on, when build finish i well notify you.
