name: Build R7800 OpenWrt

on:
  push:
    branches:
      - 'main'

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Maximize Build Space
      uses: fenghshia/f-openwrt-build@env-init
      with:
        token: ${{ secrets.TELTOKEN }}
        chatid: ${{ secrets.TELCHATID }}

    - name: Checkout config
      uses: actions/checkout@main
      with:
        ref: main

    - name: Prepare Openwrt
      run: |
        echo "拉取openwrt源码"
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo 'src-git kenzo https://github.com/kenzok8/openwrt-packages' >> feeds.conf.default
        echo 'src-git small https://github.com/kenzok8/small' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        git clone https://github.com/rufengsuixing/luci-app-zerotier.git package/luci-app-zerotier
        cp ../config/R7800.config openwrt/.config
        make download -j8

    - name: Notify prepared
      uses: appleboy/telegram-action@master
      with:
        token: ${{ secrets.TELTOKEN }}
        to: ${{ secrets.TELCHATID }}
        message: Prepare environment complete.

    - name: Set stream log
      uses: fenghshia/f-openwrt-build@online-log
      with:
        token: ${{ secrets.TELTOKEN }}
        chatid: ${{ secrets.TELCHATID }}

    - name: Build openwrt
      id: build
      run: |
        cd openwrt
        make -j$(nproc) V=s >> ../build.log

    - name: Upload img
      uses: appleboy/telegram-action@master
      with:
        token: ${{ secrets.TELTOKEN }}
        to: ${{ secrets.TELCHATID }}
        message:  image file
        document: openwrt/bin/targets/*/*/*.img
